# Generated by Django 3.0.3 on 2020-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=50)),
                ('E_mail', models.CharField(max_length=50)),
                ('Business_Phone', models.CharField(max_length=25)),
                ('Home_Phone', models.CharField(max_length=25)),
                ('Mobile_Phone', models.CharField(max_length=25)),
                ('Fax_Number', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('State_Province', models.CharField(max_length=50)),
                ('ZIP_PostalCode', models.CharField(max_length=50)),
                ('Country_Region', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=250)),
            ],
        ),
    ]
